[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "cairosvg>=2.8.2",
    "chess>=1.11.2",
    "python-chess>=1.999",
    "python-telegram-bot==21.7",
]
